services:
    whoami:
        image: traefik/whoami
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`whoami.home.spyr.dev`)"
            - "traefik.http.services.whoami.loadbalancer.server.port=443"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.routers.whoami.tls.certresolver=porkbun"
            - "traefik.http.routers.whoami.middlewares=authentik@docker"
        environment:
            - "WHOAMI_PORT_NUMBER=443"
        networks:
            - traefik

networks:
    traefik:
        external: true
