services:
    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.adminer.rule=Host(`adminer.home.spyr.dev`)"
            - "traefik.http.services.adminer.loadbalancer.server.port=8080"
            - "traefik.http.routers.adminer.entrypoints=websecure"
            - "traefik.http.routers.adminer.tls.certresolver=porkbun"
            - "traefik.http.routers.adminer.middlewares=authentik@docker"

networks:
    traefik:
        external: true
