services:
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.home.spyr.dev`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=porkbun"
      - "traefik.http.middlewares.basic-auth.basicauth.usersfile=/run/secrets/usersfile"
      - "traefik.http.routers.adminer.middlewares=basic-auth"

networks:
  traefik:
    external: true