services:
    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - downloads:/downloads
            - /mnt/music:/music
            - /opt/configs/lidarr/lidarr_config:/config
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.lidarr.rule=Host(`lidarr.home.spyr.dev`)"
            - "traefik.http.routers.lidarr.entrypoints=websecure"
            - "traefik.http.routers.lidarr.tls=true"
            - "traefik.http.routers.lidarr.tls.certresolver=porkbun"
            - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
        networks:
            - traefik

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - WEBUI_PORT=8080
            - TORRENTING_PORT=6881
        volumes:
            - /opt/configs/lidarr/qbittorrent_config:/config
            - downloads:/downloads
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.home.spyr.dev`)"
            - "traefik.http.routers.qbittorrent.entrypoints=websecure"
            - "traefik.http.routers.qbittorrent.tls=true"
            - "traefik.http.routers.qbittorrent.tls.certresolver=porkbun"
            - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
        networks:
            - traefik

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /opt/configs/lidarr/prowlarr_data:/data
            - /opt/configs/lidarr/prowlarr_config:/config
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.spyr.dev`)"
            - "traefik.http.routers.prowlarr.entrypoints=websecure"
            - "traefik.http.routers.prowlarr.tls=true"
            - "traefik.http.routers.prowlarr.tls.certresolver=porkbun"
            - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
        networks:
            - traefik

    # TODO: add bitmagnet
    # TODO: add soulseek (Soularr, Slskd)
    # TODO: add usenet

    navidrome:
        image: deluan/navidrome:latest
        container_name: navidrome
        user: 1000:1000
        restart: unless-stopped
        environment:
            ND_BASEURL: "https://music.spyr.dev"
        volumes:
            - /opt/configs/lidarr/navidrome_data:/data
            - /mnt/music:/music:ro
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.music.rule=Host(`music.spyr.dev`)"
            - "traefik.http.routers.music.entrypoints=websecure"
            - "traefik.http.routers.music.tls=true"
            - "traefik.http.routers.music.tls.certresolver=porkbun"
            - "traefik.http.services.music.loadbalancer.server.port=4533"
        networks:
            - traefik

    slskd:
        image: slskd/slskd
        container_name: slskd
        environment:
            - SLSKD_REMOTE_CONFIGURATION=true
        volumes:
            - /opt/configs/lidarr/slskd_data:/app
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.slskd.rule=Host(`slskd.home.spyr.dev`)"
            - "traefik.http.routers.slskd.entrypoints=websecure"
            - "traefik.http.routers.slskd.tls=true"
            - "traefik.http.routers.slskd.tls.certresolver=porkbun"
            - "traefik.http.services.slskd.loadbalancer.server.port=5030"
            - "traefik.http.routers.slskd.middlewares=authentik@docker"
        networks:
            - traefik

networks:
    traefik:
        external: true

volumes:
    downloads:
