services:
    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - /mnt/music:/music
            - /opt/configs/lidarr/lidarr_config:/config
            - /opt/configs/lidarr/slskd_downloads:/slskd_downloads
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.lidarr.rule=Host(`lidarr.home.spyr.dev`)"
            - "traefik.http.routers.lidarr.entrypoints=websecure"
            - "traefik.http.routers.lidarr.tls=true"
            - "traefik.http.routers.lidarr.tls.certresolver=porkbun"
            - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
        networks:
            - traefik
            - default

    navidrome:
        image: deluan/navidrome:latest
        container_name: navidrome
        user: 1000:1000
        restart: unless-stopped
        environment:
            ND_BASEURL: "https://music.spyr.dev"
        volumes:
            - /opt/configs/lidarr/navidrome_data:/data
            - /mnt/music:/music:ro
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.music.rule=Host(`music.spyr.dev`)"
            - "traefik.http.routers.music.entrypoints=websecure"
            - "traefik.http.routers.music.tls=true"
            - "traefik.http.routers.music.tls.certresolver=porkbun"
            - "traefik.http.services.music.loadbalancer.server.port=4533"
        networks:
            - traefik

    slskd:
        image: slskd/slskd
        container_name: slskd
        user: 1000:1000
        environment:
            - SLSKD_REMOTE_CONFIGURATION=true
        ports:
            - "50300:50300"
        volumes:
            - /opt/configs/lidarr/slskd_downloads:/downloads
            - /opt/configs/lidarr/slskd_data:/app
            - /mnt/music:/music:ro
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.slskd.rule=Host(`slskd.home.spyr.dev`)"
            - "traefik.http.routers.slskd.entrypoints=websecure"
            - "traefik.http.routers.slskd.tls=true"
            - "traefik.http.routers.slskd.tls.certresolver=porkbun"
            - "traefik.http.services.slskd.loadbalancer.server.port=5030"
            - "traefik.http.routers.slskd.middlewares=authentik@docker"
        networks:
            - traefik
            - default

    soularr:
        image: mrusse08/soularr:latest
        container_name: soularr
        hostname: soularr
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - SCRIPT_INTERVAL=300
        depends_on:
            - slskd
            - lidarr
        user: "1000:1000"
        volumes:
            - /opt/configs/lidarr/slskd_downloads:/downloads
            - /opt/configs/lidarr/soularr_data:/data
        networks:
            - default

    picard:
        image: mikenye/picard:latest
        container_name: picard
        volumes:
            - /opt/configs/lidarr/picard_config:/config
            - /mnt/music:/music
            - /opt/configs/lidarr/slskd_downloads:/slskd_downloads
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.picard.rule=Host(`picard.home.spyr.dev`)"
            - "traefik.http.routers.picard.entrypoints=websecure"
            - "traefik.http.routers.picard.tls=true"
            - "traefik.http.routers.picard.tls.certresolver=porkbun"
            - "traefik.http.services.picard.loadbalancer.server.port=5800"
            - "traefik.http.routers.picard.middlewares=authentik@docker"
        networks:
            - traefik

networks:
    traefik:
        external: true
