services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - DELETE_FILE_ON_TRASHCAN=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.metube.rule=Host(`dl.home.spyr.dev`)"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
      - "traefik.http.routers.metube.tls=true"
      - "traefik.http.routers.metube.tls.certresolver=porkbun"
      - "traefik.http.routers.metube.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - metube_data:/downloads
    networks:
      - traefik

volumes:
  metube_data:

networks:
  traefik:
    external: true