services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - /opt/configs/secrets/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: